import fs = require('fs');
import { Observable } from 'rxjs';

const major = 0;
const minor = 1;

let exec = require('child_process').exec;

const revision = new Observable<string>(s => {
    exec('git rev-parse --short HEAD',
        function (error: Error, stdout: Buffer, stderr: Buffer) {
            if (error !== null) {
                console.log('git error: ' + error + stderr);
            }
            s.next(stdout.toString().trim());
            s.complete();
        });
});

const branch = new Observable<string>(s => {
    exec('git rev-parse --abbrev-ref HEAD',
        function (error: Error, stdout: Buffer, stderr: Buffer) {
            if (error !== null) {
                console.log('git error: ' + error + stderr);
            }
            s.next(stdout.toString().trim());
            s.complete();
        });
});

const commitCount = new Observable<string>(s => {
    exec('git rev-list --count HEAD',
        function (error: Error, stdout: Buffer, stderr: Buffer) {
            if (error !== null) {
                console.log('git error: ' + error + stderr);
            }
            s.next(stdout.toString().trim());
            s.complete();
        });
});

Observable
    .combineLatest(revision, branch, commitCount)
    .subscribe(([revision, branch, commitCount]) => {
        console.log(`versionInfo: '${process.env.npm_package_version}', revision: '${revision}', branch: '${branch}', buildNo: '${process.env.npm_package_version}.${commitCount}'`);

        const content = '// this file is automatically generated by git.version.ts script\n' +
            `export const versionInfo = {version: '${process.env.npm_package_version}', revision: '${revision}', branch: '${branch}', buildNo: '${process.env.npm_package_version}.${commitCount}'};`;

        fs.writeFileSync(
            'src/environments/version.ts',
            content,
            {encoding: 'utf8'}
        );
    });